### ISSUE TITLE
How do we upload here!!!

### ISSUE THREAD

**Issue by saygindogu** [verobla/Shouting-Big-Data#1]
I tried to upload the project here but only thing I can do is to create a new respitory and push there. I am tearing my hairs to push the java project here but I cannot succeed. Can you please guide me! This was the same problem I have, I hate github!!!

**Comment by verobla** [comment]
You have to click on ‘+’ then ‘clone’ then select the corresponding repository (shouting big data)

Then they will ask you a folder where you want to put the content of the repository on your computer.

And then you have to put your project in the folder and synchronize. It will first show you the uncommitted changes and the conflicts. Solve/accept them and synchronize again :)

Good luck!

De : saygindogu [mailto:notifications@github.com] 
Envoyé : mardi 13 janvier 2015 12:18
À : verobla/Shouting-Big-Data
Objet : [Shouting-Big-Data] How do we upload here!!! (#1)

I tried to upload the project here but only thing I can do is to create a new respitory and push there. I am tearing my hairs to push the java project here but I cannot succeed. Can you please guide me! This was the same problem I have, I hate github!!!

**Comment by saygindogu** [comment]
I finally managed to use gitHub now, it's actually quite useful but starting to use it is hard...
