### ISSUE TITLE
Mapreduce task for counting all words

### ISSUE THREAD

**Issue by saygindogu** [verobla/Shouting-Big-Data#2]
Hello, I tried to count all distinct words and all distinct shouting words to get a percentage which could be useful, but it is not working perfectly now, so if we need it, I can spend some more time on that, but if we don't need it I will leave it.

**Comment by verobla** [comment]
You should try ;) I mean it's one of our objectives, isn't it?

**Comment by saygindogu** [comment]
It wasn't one of our objectives, but I did that for curiosity :smile:  not we can add it to our results. 

To be clear on what I did:

It counts all uppercase shouting words, all other words, and all words which give exception ( I don't know why.. but we can say these are not shouting :8ball: )

We had an objective which is to count how many tweets are shouting and how many are not shouting, (this regards tweets with "!" also and not in the word level, but tweet level ) but I think it is included in Faustine's part.
